# Demo code

In [7]:
import numpy as np
import torch
import gc

In [10]:
gc.collect()

864

### Stack 2 or several arrays

In [15]:
# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Convert NumPy arrays to PyTorch tensors
tensor1 = torch.as_tensor(array1)
tensor2 = torch.as_tensor(array2)

# Stack the tensors along a new dimension (dim=0)
stacked_tensor = torch.stack((tensor1, tensor2), dim=0)
print("Stacked Tensor:\n", stacked_tensor, stacked_tensor.shape)

Stacked Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


In [17]:
# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays along a new dimension
stacked_array = np.stack((array1, array2, array1))
print("Stacked Array:\n", stacked_array, stacked_array.shape)

# Stack the arrays vertically
vstacked_array = np.vstack((array1, array2))
print("Vertically Stacked Array:\n", vstacked_array, vstacked_array.shape)

Stacked Array:
 [[1 2 3]
 [4 5 6]
 [1 2 3]] (3, 3)
Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]] (2, 3)


torch.Size([2, 3])
